name: Update

permissions:
  contents: write
  
on:
  schedule:
    - cron: '0 13,17 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run update
        run: echo COMMIT_MESSAGE="$(./update.sh > out && cat out | head -n 1 && rm out)" >> $GITHUB_ENV

      - name: Commit and push changes
        if: env.COMMIT_MESSAGE != 'Already up to date'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add default.nix
          git commit -m "${{ env.COMMIT_MESSAGE }}"
          git push
